- name: Deploys blue-green template
  template: >
    src="../templates/blue-green.conf.j2" 
    dest=/etc/haproxy/conf.d/50_{{ haproxy_blue_green_name }}.cfg
  with_items: groups[haproxy_blue_green_loadbalancers]
  delegate_to: "{{ item }}"
  notify: Restart loadbalancers

